name: NetPulseMobile
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.cwzs.netpulse
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 2.1.0
    CURRENT_PROJECT_VERSION: 1
targets:
  NetPulseMobile:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Core
      - path: Domain
      - path: Features
      - path: Shared
      - path: Resources
    info:
      path: Resources/Info.plist
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: NO
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
